import { autocompletion, type Completion, type CompletionContext, snippetCompletion } from '@codemirror/autocomplete'

const commands: { label: string; detail: string }[] = [
  { label: '\\section', detail: 'section heading' },
  { label: '\\subsection', detail: 'subsection heading' },
  { label: '\\subsubsection', detail: 'subsubsection heading' },
  { label: '\\paragraph', detail: 'paragraph heading' },
  { label: '\\subparagraph', detail: 'subparagraph heading' },
  { label: '\\chapter', detail: 'chapter heading' },
  { label: '\\title', detail: 'document title' },
  { label: '\\author', detail: 'document author' },
  { label: '\\date', detail: 'document date' },
  { label: '\\maketitle', detail: 'generate title' },
  { label: '\\tableofcontents', detail: 'table of contents' },
  { label: '\\listoffigures', detail: 'list of figures' },
  { label: '\\listoftables', detail: 'list of tables' },
  { label: '\\newpage', detail: 'force new page' },
  { label: '\\clearpage', detail: 'clear floats and new page' },
  { label: '\\pagebreak', detail: 'suggested page break' },
  { label: '\\nopagebreak', detail: 'prevent page break' },
  { label: '\\linebreak', detail: 'suggested line break' },
  { label: '\\nolinebreak', detail: 'prevent line break' },
  { label: '\\newline', detail: 'force new line' },
  { label: '\\hfill', detail: 'horizontal fill' },
  { label: '\\vfill', detail: 'vertical fill' },
  { label: '\\hspace', detail: 'horizontal space' },
  { label: '\\vspace', detail: 'vertical space' },
  { label: '\\bigskip', detail: 'big vertical skip' },
  { label: '\\medskip', detail: 'medium vertical skip' },
  { label: '\\smallskip', detail: 'small vertical skip' },
  { label: '\\textbf', detail: 'bold text' },
  { label: '\\textit', detail: 'italic text' },
  { label: '\\texttt', detail: 'monospaced text' },
  { label: '\\textsf', detail: 'sans-serif text' },
  { label: '\\textsc', detail: 'small caps text' },
  { label: '\\textsl', detail: 'slanted text' },
  { label: '\\emph', detail: 'emphasized text' },
  { label: '\\underline', detail: 'underlined text' },
  { label: '\\uppercase', detail: 'uppercase text' },
  { label: '\\lowercase', detail: 'lowercase text' },
  { label: '\\rmfamily', detail: 'roman font family' },
  { label: '\\sffamily', detail: 'sans-serif font family' },
  { label: '\\ttfamily', detail: 'monospaced font family' },
  { label: '\\bfseries', detail: 'bold font series' },
  { label: '\\itshape', detail: 'italic shape' },
  { label: '\\scshape', detail: 'small caps shape' },
  { label: '\\tiny', detail: 'tiny font size' },
  { label: '\\scriptsize', detail: 'script size' },
  { label: '\\footnotesize', detail: 'footnote size' },
  { label: '\\small', detail: 'small font size' },
  { label: '\\normalsize', detail: 'normal font size' },
  { label: '\\large', detail: 'large font size' },
  { label: '\\Large', detail: 'Larger font size' },
  { label: '\\LARGE', detail: 'very large font size' },
  { label: '\\huge', detail: 'huge font size' },
  { label: '\\Huge', detail: 'very huge font size' },
  { label: '\\cite', detail: 'citation' },
  { label: '\\nocite', detail: 'uncited reference' },
  { label: '\\bibliography', detail: 'bibliography source' },
  { label: '\\bibliographystyle', detail: 'bibliography style' },
  { label: '\\ref', detail: 'cross reference' },
  { label: '\\eqref', detail: 'equation reference' },
  { label: '\\pageref', detail: 'page reference' },
  { label: '\\label', detail: 'set label' },
  { label: '\\item', detail: 'list item' },
  { label: '\\frac', detail: 'fraction' },
  { label: '\\sqrt', detail: 'square root' },
  { label: '\\sum', detail: 'summation' },
  { label: '\\prod', detail: 'product' },
  { label: '\\int', detail: 'integral' },
  { label: '\\iint', detail: 'double integral' },
  { label: '\\iiint', detail: 'triple integral' },
  { label: '\\oint', detail: 'contour integral' },
  { label: '\\infty', detail: 'infinity' },
  { label: '\\pm', detail: 'plus-minus' },
  { label: '\\mp', detail: 'minus-plus' },
  { label: '\\times', detail: 'multiplication' },
  { label: '\\div', detail: 'division' },
  { label: '\\leq', detail: 'less than or equal' },
  { label: '\\geq', detail: 'greater than or equal' },
  { label: '\\neq', detail: 'not equal' },
  { label: '\\approx', detail: 'approximately' },
  { label: '\\equiv', detail: 'equivalent' },
  { label: '\\rightarrow', detail: 'right arrow' },
  { label: '\\leftarrow', detail: 'left arrow' },
  { label: '\\Rightarrow', detail: 'double right arrow' },
  { label: '\\Leftarrow', detail: 'double left arrow' },
  { label: '\\leftrightarrow', detail: 'left-right arrow' },
  { label: '\\cdot', detail: 'center dot' },
  { label: '\\ldots', detail: 'ellipsis' },
  { label: '\\cdots', detail: 'centered ellipsis' },
  { label: '\\alpha', detail: 'Greek letter alpha' },
  { label: '\\beta', detail: 'Greek letter beta' },
  { label: '\\gamma', detail: 'Greek letter gamma' },
  { label: '\\delta', detail: 'Greek letter delta' },
  { label: '\\epsilon', detail: 'Greek letter epsilon' },
  { label: '\\zeta', detail: 'Greek letter zeta' },
  { label: '\\eta', detail: 'Greek letter eta' },
  { label: '\\theta', detail: 'Greek letter theta' },
  { label: '\\iota', detail: 'Greek letter iota' },
  { label: '\\kappa', detail: 'Greek letter kappa' },
  { label: '\\lambda', detail: 'Greek letter lambda' },
  { label: '\\mu', detail: 'Greek letter mu' },
  { label: '\\nu', detail: 'Greek letter nu' },
  { label: '\\xi', detail: 'Greek letter xi' },
  { label: '\\omicron', detail: 'Greek letter omicron' },
  { label: '\\pi', detail: 'Greek letter pi' },
  { label: '\\rho', detail: 'Greek letter rho' },
  { label: '\\sigma', detail: 'Greek letter sigma' },
  { label: '\\tau', detail: 'Greek letter tau' },
  { label: '\\upsilon', detail: 'Greek letter upsilon' },
  { label: '\\phi', detail: 'Greek letter phi' },
  { label: '\\chi', detail: 'Greek letter chi' },
  { label: '\\psi', detail: 'Greek letter psi' },
  { label: '\\omega', detail: 'Greek letter omega' },
  { label: '\\Gamma', detail: 'Greek letter Gamma' },
  { label: '\\Delta', detail: 'Greek letter Delta' },
  { label: '\\Theta', detail: 'Greek letter Theta' },
  { label: '\\Lambda', detail: 'Greek letter Lambda' },
  { label: '\\Xi', detail: 'Greek letter Xi' },
  { label: '\\Pi', detail: 'Greek letter Pi' },
  { label: '\\Sigma', detail: 'Greek letter Sigma' },
  { label: '\\Upsilon', detail: 'Greek letter Upsilon' },
  { label: '\\Phi', detail: 'Greek letter Phi' },
  { label: '\\Psi', detail: 'Greek letter Psi' },
  { label: '\\Omega', detail: 'Greek letter Omega' },
  { label: '\\begin', detail: 'begin environment' },
  { label: '\\end', detail: 'end environment' },
  { label: '\\documentclass', detail: 'document class' },
  { label: '\\usepackage', detail: 'load package' },
  { label: '\\includegraphics', detail: 'insert image' },
  { label: '\\caption', detail: 'figure/table caption' },
  { label: '\\footnote', detail: 'footnote' },
  { label: '\\url', detail: 'typeset URL' },
  { label: '\\href', detail: 'hyperlinked URL' },
  { label: '\\input', detail: 'input file' },
  { label: '\\include', detail: 'include file' },
  { label: '\\newcommand', detail: 'define command' },
  { label: '\\renewcommand', detail: 'redefine command' },
  { label: '\\DeclareMathOperator', detail: 'declare math operator' },
  { label: '\\left', detail: 'left delimiter' },
  { label: '\\right', detail: 'right delimiter' },
  { label: '\\begin{document}', detail: 'document body' },
  { label: '\\begin{abstract}', detail: 'abstract environment' }
]

const environments = [
  'document',
  'itemize',
  'enumerate',
  'equation',
  'align',
  'figure',
  'table',
  'center',
  'verbatim',
  'quote',
  'minipage'
]

const envCompletions: Completion[] = environments.map((env) =>
  snippetCompletion('\\begin{' + env + '}\n\t${cursor}\n\\end{' + env + '}', {
    label: '\\begin{' + env + '}',
    detail: env + ' environment'
  })
)

const commandCompletions: Completion[] = commands.map((c) => ({
  label: c.label,
  detail: c.detail
}))

const allCompletions = [...commandCompletions, ...envCompletions]

function latexCompletionSource(context: CompletionContext) {
  const word = context.matchBefore(/\\[A-Za-z]*$/)
  if (!word) return null
  return {
    from: word.from,
    options: allCompletions,
    validFor: /^\\[A-Za-z]*$/
  }
}

export const latexAutocompleteExtension = autocompletion({
  override: [latexCompletionSource],
  defaultKeymap: true
})
